# Generated by Django 5.1.7 on 2025-04-17 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 17, 16, 16, 1, 249882)),
        ),
    ]
