# Generated by Django 5.1.7 on 2025-04-17 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 17, 18, 22, 2, 403514)),
        ),
    ]
