# Generated by Django 5.1.7 on 2025-04-19 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_publish_date_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 19, 18, 42, 9, 323521)),
        ),
    ]
