# Generated by Django 5.1.7 on 2025-04-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=35)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('join_date', models.DateTimeField(auto_now=True)),
                ('email_addr', models.EmailField(max_length=25)),
                ('phone_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage/static/assets/img/profiles')),
            ],
        ),
    ]
