# Generated by Django 5.1.7 on 2025-04-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email_addr',
            field=models.EmailField(max_length=100),
        ),
    ]
