# Generated by Django 5.1.7 on 2025-04-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_email_addr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messeage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email_addr', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('messeage', models.TextField(max_length=1000)),
            ],
        ),
    ]
