# Generated by Django 5.1.7 on 2025-04-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_messeage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messeage',
            old_name='messeage',
            new_name='message',
        ),
        migrations.AddField(
            model_name='messeage',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
